import type { Product } from "./productTypes"

export const productsData: Product[] = [
  {
    id: "PRD-001",
    name: "POS Terminal T20",
    category: "informatique",
    purchasePrice: 85000,
    salePrice: 120000,
    quantity: 14,
    createdAt: "2026-01-12",
    salesHistory: [
      {
        id: "SAL-1001",
        date: "2026-05-07",
        quantity: 2,
        unitPrice: 120000,
        total: 240000,
        invoiceRef: "FAC-9021",
        clientName: "Awa Traore",
      },
      {
        id: "SAL-1002",
        date: "2026-04-29",
        quantity: 1,
        unitPrice: 118000,
        total: 118000,
        invoiceRef: "FAC-8942",
        clientName: "Moussa Kone",
      },
    ],
    stockMovements: [
      {
        id: "MOV-1001",
        date: "2026-05-08",
        type: "in",
        quantity: 6,
        reason: "Reapprovisionnement fournisseur",
        reference: "BON-4421",
      },
      {
        id: "MOV-1002",
        date: "2026-05-07",
        type: "out",
        quantity: 2,
        reason: "Vente client",
        reference: "FAC-9021",
      },
    ],
  },
  {
    id: "PRD-002",
    name: "Routeur 5G Pro",
    category: "informatique",
    purchasePrice: 38000,
    salePrice: 56000,
    quantity: 4,
    createdAt: "2025-12-02",
    salesHistory: [
      {
        id: "SAL-2001",
        date: "2026-05-04",
        quantity: 1,
        unitPrice: 56000,
        total: 56000,
        invoiceRef: "FAC-9007",
        clientName: "Ibrahim Coulibaly",
      },
    ],
    stockMovements: [
      {
        id: "MOV-2001",
        date: "2026-05-04",
        type: "out",
        quantity: 1,
        reason: "Vente client",
        reference: "FAC-9007",
      },
      {
        id: "MOV-2002",
        date: "2026-04-28",
        type: "adjustment",
        quantity: -1,
        reason: "Ajustement inventaire",
      },
    ],
  },
  {
    id: "PRD-003",
    name: "Micro-onde Nova 30L",
    category: "electromenager",
    purchasePrice: 52000,
    salePrice: 76000,
    quantity: 0,
    createdAt: "2025-11-17",
    salesHistory: [
      {
        id: "SAL-3001",
        date: "2026-05-01",
        quantity: 1,
        unitPrice: 76000,
        total: 76000,
        invoiceRef: "FAC-8990",
        clientName: "Fatou Diallo",
      },
    ],
    stockMovements: [
      {
        id: "MOV-3001",
        date: "2026-05-01",
        type: "out",
        quantity: 1,
        reason: "Vente client",
        reference: "FAC-8990",
      },
    ],
  },
  {
    id: "PRD-004",
    name: "Balance connectee S2",
    category: "accessoire",
    purchasePrice: 9000,
    salePrice: 14500,
    quantity: 21,
    createdAt: "2026-02-03",
    salesHistory: [
      {
        id: "SAL-4001",
        date: "2026-05-03",
        quantity: 3,
        unitPrice: 14500,
        total: 43500,
        invoiceRef: "FAC-9011",
        clientName: "Awa Traore",
      },
    ],
    stockMovements: [
      {
        id: "MOV-4001",
        date: "2026-05-03",
        type: "out",
        quantity: 3,
        reason: "Vente client",
        reference: "FAC-9011",
      },
      {
        id: "MOV-4002",
        date: "2026-04-20",
        type: "in",
        quantity: 10,
        reason: "Reapprovisionnement",
        reference: "BON-4356",
      },
    ],
  },
  {
    id: "PRD-005",
    name: "Cartouche imprimante X1",
    category: "consommable",
    purchasePrice: 4200,
    salePrice: 7000,
    quantity: 32,
    createdAt: "2026-03-09",
    salesHistory: [
      {
        id: "SAL-5001",
        date: "2026-05-05",
        quantity: 5,
        unitPrice: 7000,
        total: 35000,
        invoiceRef: "FAC-9018",
        clientName: "Moussa Kone",
      },
    ],
    stockMovements: [
      {
        id: "MOV-5001",
        date: "2026-05-05",
        type: "out",
        quantity: 5,
        reason: "Vente client",
        reference: "FAC-9018",
      },
    ],
  },
  {
    id: "PRD-006",
    name: "Clavier mecanique K87",
    category: "informatique",
    purchasePrice: 18000,
    salePrice: 29000,
    quantity: 7,
    createdAt: "2026-01-23",
    salesHistory: [],
    stockMovements: [
      {
        id: "MOV-6001",
        date: "2026-04-30",
        type: "in",
        quantity: 7,
        reason: "Reapprovisionnement",
        reference: "BON-4411",
      },
    ],
  },
  {
    id: "PRD-007",
    name: "Frigo compact 120L",
    category: "electromenager",
    purchasePrice: 98000,
    salePrice: 132000,
    quantity: 3,
    createdAt: "2026-02-18",
    salesHistory: [
      {
        id: "SAL-7001",
        date: "2026-05-02",
        quantity: 1,
        unitPrice: 132000,
        total: 132000,
        invoiceRef: "FAC-9002",
        clientName: "Ibrahim Coulibaly",
      },
    ],
    stockMovements: [
      {
        id: "MOV-7001",
        date: "2026-05-02",
        type: "out",
        quantity: 1,
        reason: "Vente client",
        reference: "FAC-9002",
      },
    ],
  },
  {
    id: "PRD-008",
    name: "Batterie externe 20k",
    category: "accessoire",
    purchasePrice: 6800,
    salePrice: 11500,
    quantity: 18,
    createdAt: "2026-04-01",
    salesHistory: [],
    stockMovements: [
      {
        id: "MOV-8001",
        date: "2026-04-01",
        type: "in",
        quantity: 18,
        reason: "Stock initial",
        reference: "INIT-008",
      },
    ],
  },
]

export function getProductById(productId: string) {
  return productsData.find((product) => product.id === productId)
}
