import type { StockItem, StockMovement } from "./stockTypes"

export const stockItemsData: StockItem[] = [
  {
    id: "STK-001",
    productId: "PRD-001",
    productName: "POS Terminal T20",
    category: "Informatique",
    quantityAvailable: 14,
    lowThreshold: 5,
    updatedAt: "2026-05-08",
  },
  {
    id: "STK-002",
    productId: "PRD-002",
    productName: "Routeur 5G Pro",
    category: "Informatique",
    quantityAvailable: 4,
    lowThreshold: 6,
    updatedAt: "2026-05-07",
  },
  {
    id: "STK-003",
    productId: "PRD-003",
    productName: "Micro-onde Nova 30L",
    category: "Electromenager",
    quantityAvailable: 0,
    lowThreshold: 3,
    updatedAt: "2026-05-06",
  },
  {
    id: "STK-004",
    productId: "PRD-004",
    productName: "Balance connectee S2",
    category: "Accessoire",
    quantityAvailable: 21,
    lowThreshold: 8,
    updatedAt: "2026-05-08",
  },
  {
    id: "STK-005",
    productId: "PRD-005",
    productName: "Cartouche imprimante X1",
    category: "Consommable",
    quantityAvailable: 32,
    lowThreshold: 10,
    updatedAt: "2026-05-05",
  },
  {
    id: "STK-006",
    productId: "PRD-007",
    productName: "Frigo compact 120L",
    category: "Electromenager",
    quantityAvailable: 3,
    lowThreshold: 5,
    updatedAt: "2026-05-02",
  },
]

export const stockMovementsData: StockMovement[] = [
  {
    id: "MV-001",
    date: "2026-05-08",
    productId: "PRD-001",
    productName: "POS Terminal T20",
    type: "in",
    quantity: 6,
    reason: "Reapprovisionnement fournisseur",
    reference: "BON-4421",
  },
  {
    id: "MV-002",
    date: "2026-05-07",
    productId: "PRD-002",
    productName: "Routeur 5G Pro",
    type: "out",
    quantity: 1,
    reason: "Vente client",
    reference: "FAC-9007",
  },
  {
    id: "MV-003",
    date: "2026-05-06",
    productId: "PRD-003",
    productName: "Micro-onde Nova 30L",
    type: "out",
    quantity: 1,
    reason: "Vente client",
    reference: "FAC-8990",
  },
  {
    id: "MV-004",
    date: "2026-05-04",
    productId: "PRD-004",
    productName: "Balance connectee S2",
    type: "adjustment",
    quantity: -2,
    reason: "Correction inventaire",
    reference: "INV-112",
  },
  {
    id: "MV-005",
    date: "2026-05-03",
    productId: "PRD-005",
    productName: "Cartouche imprimante X1",
    type: "in",
    quantity: 12,
    reason: "Entree stock periodic",
    reference: "BON-4400",
  },
  {
    id: "MV-006",
    date: "2026-05-02",
    productId: "PRD-007",
    productName: "Frigo compact 120L",
    type: "out",
    quantity: 1,
    reason: "Vente client",
    reference: "FAC-9002",
  },
]
